### ISSUE TITLE
change the 'Enter Icon Class' hint

### ISSUE THREAD

**Issue by shoulders** [joomdev/jd_skillset#1]
The prefilled icon class is **fab fa-accusoft** , I did not know that fab class is for brands only. This means that when i try **fab fa-cog** it will not work.

Would you consider changing the prefill/hint to something like **fa fa-cog** as people are more likely to use a random icon rather than a brandname in this module.

You could put both examples below the box if you felt that was a good idea.

**Comment by chetanmadaan** [comment]
Added Icon link:
![image](https://user-images.githubusercontent.com/3968575/61479856-b6c89a80-a962-11e9-878d-f35a58853527.png)


Changed accusoft to Joomla, yaay! we are promoting Joomla now.

The new icons are fab, fas, far and fal. See here: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
